### ISSUE TITLE
exchange title screen graphics

### ISSUE THREAD

**Issue by kirijiri** [kirijiri/GalactosIntolerant#28]

**Comment by cheezopath** [comment]
what IS the title screen graphic? I don't think I've seen it...

**Comment by FireWaterGasoline** [comment]
the zoomed in concept art with galacto button? : )

**Comment by kirijiri** [comment]
when you open the game there is a screen... you click a button and the level starts.... that screen right now has just the background and the button is galacto, thats it... later it should probably have a start, maybe level select (if we ever do that), and options button .... 

right now we probably just need a nice background and start button

**Comment by FireWaterGasoline** [comment]
I think eduardo already did a mockup of the title screen so we'll have
something for them insomnias.

**Comment by cheezopath** [comment]
Yeah I'll make a sketch for the weekend and make it better in between doing mechanical art
